services:
  backend:
    image: registry.digitalocean.com/dailybruin/dbllm-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    platform: linux/amd64
    ports:
      - "5001:5001"  # Expose backend port internally (optional, if needed for debugging)

  frontend:
    image: registry.digitalocean.com/dailybruin/dbllm-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    platform: linux/amd64
    ports:
      - "5173:4173"  # Expose frontend port to the outside world